-- ============================================
-- LOAD DATA FROM STAGE INTO RAW TABLES
-- Prerequisite: all 14 CSVs uploaded to @F1_STAGE
-- (Snowsight: Databases > F1_PROJECT > RAW > Stages > F1_STAGE > + Files)
-- ============================================

USE DATABASE F1_PROJECT;
USE SCHEMA RAW;

COPY INTO DRIVERS FROM @F1_STAGE/drivers.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO CONSTRUCTORS FROM @F1_STAGE/constructors.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO CIRCUITS FROM @F1_STAGE/circuits.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO SEASONS FROM @F1_STAGE/seasons.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO RACES FROM @F1_STAGE/races.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO RESULTS FROM @F1_STAGE/results.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO SPRINT_RESULTS FROM @F1_STAGE/sprint_results.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO QUALIFYING FROM @F1_STAGE/qualifying.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO PIT_STOPS FROM @F1_STAGE/pit_stops.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO LAP_TIMES FROM @F1_STAGE/lap_times.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO DRIVER_STANDINGS FROM @F1_STAGE/driver_standings.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO CONSTRUCTOR_STANDINGS FROM @F1_STAGE/constructor_standings.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO CONSTRUCTOR_RESULTS FROM @F1_STAGE/constructor_results.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;
COPY INTO STATUS FROM @F1_STAGE/status.csv FILE_FORMAT = F1_CSV_FORMAT FORCE = TRUE;

-- Sanity checks
SELECT 'drivers' AS table_name, COUNT(*) AS row_count FROM DRIVERS
UNION ALL SELECT 'constructors', COUNT(*) FROM CONSTRUCTORS
UNION ALL SELECT 'races', COUNT(*) FROM RACES
UNION ALL SELECT 'results', COUNT(*) FROM RESULTS
UNION ALL SELECT 'pit_stops', COUNT(*) FROM PIT_STOPS
UNION ALL SELECT 'lap_times', COUNT(*) FROM LAP_TIMES
UNION ALL SELECT 'qualifying', COUNT(*) FROM QUALIFYING;